version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundles:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development

  db:
    image: sqlite3
    volumes:
      - db_data:/var/lib/sqlite3

volumes:
  node_modules:
  db_data:
  bundles: